# GitHub Sponsors funding configuration
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Lightning Network donation
custom: ['lightning:yellowbobcat7@primal.net', 'https://primal.net/yellowbobcat7']
