/**
 * Comprehensive list of all countries organized by region
 */

export interface Region {
  id: string;
  name: string;
}

export interface Country {
  id: string;
  name: string;
  region: string;
}

// Regions (Continents)
export const REGIONS: Region[] = [
  { id: 'africa', name: 'Africa' },
  { id: 'asia', name: 'Asia' },
  { id: 'europe', name: 'Europe' },
  { id: 'north-america', name: 'North America' },
  { id: 'south-america', name: 'South America' },
  { id: 'oceania', name: 'Oceania' },
  { id: 'antarctica', name: 'Antarctica' },
];

// All 195 countries (193 UN member states + 2 observer states)
export const COUNTRIES: Country[] = [
  // Africa (54 countries)
  { id: 'algeria', name: 'Algeria', region: 'africa' },
  { id: 'angola', name: 'Angola', region: 'africa' },
  { id: 'benin', name: 'Benin', region: 'africa' },
  { id: 'botswana', name: 'Botswana', region: 'africa' },
  { id: 'burkina-faso', name: 'Burkina Faso', region: 'africa' },
  { id: 'burundi', name: 'Burundi', region: 'africa' },
  { id: 'cabo-verde', name: 'Cabo Verde', region: 'africa' },
  { id: 'cameroon', name: 'Cameroon', region: 'africa' },
  { id: 'central-african-republic', name: 'Central African Republic', region: 'africa' },
  { id: 'chad', name: 'Chad', region: 'africa' },
  { id: 'comoros', name: 'Comoros', region: 'africa' },
  { id: 'congo-brazzaville', name: 'Congo (Brazzaville)', region: 'africa' },
  { id: 'congo-kinshasa', name: 'Congo (Kinshasa)', region: 'africa' },
  { id: 'cote-divoire', name: "Côte d'Ivoire", region: 'africa' },
  { id: 'djibouti', name: 'Djibouti', region: 'africa' },
  { id: 'egypt', name: 'Egypt', region: 'africa' },
  { id: 'equatorial-guinea', name: 'Equatorial Guinea', region: 'africa' },
  { id: 'eritrea', name: 'Eritrea', region: 'africa' },
  { id: 'eswatini', name: 'Eswatini', region: 'africa' },
  { id: 'ethiopia', name: 'Ethiopia', region: 'africa' },
  { id: 'gabon', name: 'Gabon', region: 'africa' },
  { id: 'gambia', name: 'Gambia', region: 'africa' },
  { id: 'ghana', name: 'Ghana', region: 'africa' },
  { id: 'guinea', name: 'Guinea', region: 'africa' },
  { id: 'guinea-bissau', name: 'Guinea-Bissau', region: 'africa' },
  { id: 'kenya', name: 'Kenya', region: 'africa' },
  { id: 'lesotho', name: 'Lesotho', region: 'africa' },
  { id: 'liberia', name: 'Liberia', region: 'africa' },
  { id: 'libya', name: 'Libya', region: 'africa' },
  { id: 'madagascar', name: 'Madagascar', region: 'africa' },
  { id: 'malawi', name: 'Malawi', region: 'africa' },
  { id: 'mali', name: 'Mali', region: 'africa' },
  { id: 'mauritania', name: 'Mauritania', region: 'africa' },
  { id: 'mauritius', name: 'Mauritius', region: 'africa' },
  { id: 'morocco', name: 'Morocco', region: 'africa' },
  { id: 'mozambique', name: 'Mozambique', region: 'africa' },
  { id: 'namibia', name: 'Namibia', region: 'africa' },
  { id: 'niger', name: 'Niger', region: 'africa' },
  { id: 'nigeria', name: 'Nigeria', region: 'africa' },
  { id: 'rwanda', name: 'Rwanda', region: 'africa' },
  { id: 'sao-tome-principe', name: 'São Tomé and Príncipe', region: 'africa' },
  { id: 'senegal', name: 'Senegal', region: 'africa' },
  { id: 'seychelles', name: 'Seychelles', region: 'africa' },
  { id: 'sierra-leone', name: 'Sierra Leone', region: 'africa' },
  { id: 'somalia', name: 'Somalia', region: 'africa' },
  { id: 'south-africa', name: 'South Africa', region: 'africa' },
  { id: 'south-sudan', name: 'South Sudan', region: 'africa' },
  { id: 'sudan', name: 'Sudan', region: 'africa' },
  { id: 'tanzania', name: 'Tanzania', region: 'africa' },
  { id: 'togo', name: 'Togo', region: 'africa' },
  { id: 'tunisia', name: 'Tunisia', region: 'africa' },
  { id: 'uganda', name: 'Uganda', region: 'africa' },
  { id: 'zambia', name: 'Zambia', region: 'africa' },
  { id: 'zimbabwe', name: 'Zimbabwe', region: 'africa' },

  // Asia (48 countries)
  { id: 'afghanistan', name: 'Afghanistan', region: 'asia' },
  { id: 'armenia', name: 'Armenia', region: 'asia' },
  { id: 'azerbaijan', name: 'Azerbaijan', region: 'asia' },
  { id: 'bahrain', name: 'Bahrain', region: 'asia' },
  { id: 'bangladesh', name: 'Bangladesh', region: 'asia' },
  { id: 'bhutan', name: 'Bhutan', region: 'asia' },
  { id: 'brunei', name: 'Brunei', region: 'asia' },
  { id: 'cambodia', name: 'Cambodia', region: 'asia' },
  { id: 'china', name: 'China', region: 'asia' },
  { id: 'cyprus', name: 'Cyprus', region: 'asia' },
  { id: 'georgia', name: 'Georgia', region: 'asia' },
  { id: 'india', name: 'India', region: 'asia' },
  { id: 'indonesia', name: 'Indonesia', region: 'asia' },
  { id: 'iran', name: 'Iran', region: 'asia' },
  { id: 'iraq', name: 'Iraq', region: 'asia' },
  { id: 'israel', name: 'Israel', region: 'asia' },
  { id: 'japan', name: 'Japan', region: 'asia' },
  { id: 'jordan', name: 'Jordan', region: 'asia' },
  { id: 'kazakhstan', name: 'Kazakhstan', region: 'asia' },
  { id: 'kuwait', name: 'Kuwait', region: 'asia' },
  { id: 'kyrgyzstan', name: 'Kyrgyzstan', region: 'asia' },
  { id: 'laos', name: 'Laos', region: 'asia' },
  { id: 'lebanon', name: 'Lebanon', region: 'asia' },
  { id: 'malaysia', name: 'Malaysia', region: 'asia' },
  { id: 'maldives', name: 'Maldives', region: 'asia' },
  { id: 'mongolia', name: 'Mongolia', region: 'asia' },
  { id: 'myanmar', name: 'Myanmar', region: 'asia' },
  { id: 'nepal', name: 'Nepal', region: 'asia' },
  { id: 'north-korea', name: 'North Korea', region: 'asia' },
  { id: 'oman', name: 'Oman', region: 'asia' },
  { id: 'pakistan', name: 'Pakistan', region: 'asia' },
  { id: 'palestine', name: 'Palestine', region: 'asia' },
  { id: 'philippines', name: 'Philippines', region: 'asia' },
  { id: 'qatar', name: 'Qatar', region: 'asia' },
  { id: 'saudi-arabia', name: 'Saudi Arabia', region: 'asia' },
  { id: 'singapore', name: 'Singapore', region: 'asia' },
  { id: 'south-korea', name: 'South Korea', region: 'asia' },
  { id: 'sri-lanka', name: 'Sri Lanka', region: 'asia' },
  { id: 'syria', name: 'Syria', region: 'asia' },
  { id: 'tajikistan', name: 'Tajikistan', region: 'asia' },
  { id: 'thailand', name: 'Thailand', region: 'asia' },
  { id: 'timor-leste', name: 'Timor-Leste', region: 'asia' },
  { id: 'turkey', name: 'Turkey', region: 'asia' },
  { id: 'turkmenistan', name: 'Turkmenistan', region: 'asia' },
  { id: 'uae', name: 'United Arab Emirates', region: 'asia' },
  { id: 'uzbekistan', name: 'Uzbekistan', region: 'asia' },
  { id: 'vietnam', name: 'Vietnam', region: 'asia' },
  { id: 'yemen', name: 'Yemen', region: 'asia' },

  // Europe (44 countries)
  { id: 'albania', name: 'Albania', region: 'europe' },
  { id: 'andorra', name: 'Andorra', region: 'europe' },
  { id: 'austria', name: 'Austria', region: 'europe' },
  { id: 'belarus', name: 'Belarus', region: 'europe' },
  { id: 'belgium', name: 'Belgium', region: 'europe' },
  { id: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina', region: 'europe' },
  { id: 'bulgaria', name: 'Bulgaria', region: 'europe' },
  { id: 'croatia', name: 'Croatia', region: 'europe' },
  { id: 'czechia', name: 'Czechia', region: 'europe' },
  { id: 'denmark', name: 'Denmark', region: 'europe' },
  { id: 'estonia', name: 'Estonia', region: 'europe' },
  { id: 'finland', name: 'Finland', region: 'europe' },
  { id: 'france', name: 'France', region: 'europe' },
  { id: 'germany', name: 'Germany', region: 'europe' },
  { id: 'greece', name: 'Greece', region: 'europe' },
  { id: 'hungary', name: 'Hungary', region: 'europe' },
  { id: 'iceland', name: 'Iceland', region: 'europe' },
  { id: 'ireland', name: 'Ireland', region: 'europe' },
  { id: 'italy', name: 'Italy', region: 'europe' },
  { id: 'kosovo', name: 'Kosovo', region: 'europe' },
  { id: 'latvia', name: 'Latvia', region: 'europe' },
  { id: 'liechtenstein', name: 'Liechtenstein', region: 'europe' },
  { id: 'lithuania', name: 'Lithuania', region: 'europe' },
  { id: 'luxembourg', name: 'Luxembourg', region: 'europe' },
  { id: 'malta', name: 'Malta', region: 'europe' },
  { id: 'moldova', name: 'Moldova', region: 'europe' },
  { id: 'monaco', name: 'Monaco', region: 'europe' },
  { id: 'montenegro', name: 'Montenegro', region: 'europe' },
  { id: 'netherlands', name: 'Netherlands', region: 'europe' },
  { id: 'north-macedonia', name: 'North Macedonia', region: 'europe' },
  { id: 'norway', name: 'Norway', region: 'europe' },
  { id: 'poland', name: 'Poland', region: 'europe' },
  { id: 'portugal', name: 'Portugal', region: 'europe' },
  { id: 'romania', name: 'Romania', region: 'europe' },
  { id: 'russia', name: 'Russia', region: 'europe' },
  { id: 'san-marino', name: 'San Marino', region: 'europe' },
  { id: 'serbia', name: 'Serbia', region: 'europe' },
  { id: 'slovakia', name: 'Slovakia', region: 'europe' },
  { id: 'slovenia', name: 'Slovenia', region: 'europe' },
  { id: 'spain', name: 'Spain', region: 'europe' },
  { id: 'sweden', name: 'Sweden', region: 'europe' },
  { id: 'switzerland', name: 'Switzerland', region: 'europe' },
  { id: 'ukraine', name: 'Ukraine', region: 'europe' },
  { id: 'united-kingdom', name: 'United Kingdom', region: 'europe' },
  { id: 'vatican-city', name: 'Vatican City', region: 'europe' },

  // North America (23 countries)
  { id: 'antigua-barbuda', name: 'Antigua and Barbuda', region: 'north-america' },
  { id: 'bahamas', name: 'Bahamas', region: 'north-america' },
  { id: 'barbados', name: 'Barbados', region: 'north-america' },
  { id: 'belize', name: 'Belize', region: 'north-america' },
  { id: 'canada', name: 'Canada', region: 'north-america' },
  { id: 'costa-rica', name: 'Costa Rica', region: 'north-america' },
  { id: 'cuba', name: 'Cuba', region: 'north-america' },
  { id: 'dominica', name: 'Dominica', region: 'north-america' },
  { id: 'dominican-republic', name: 'Dominican Republic', region: 'north-america' },
  { id: 'el-salvador', name: 'El Salvador', region: 'north-america' },
  { id: 'grenada', name: 'Grenada', region: 'north-america' },
  { id: 'guatemala', name: 'Guatemala', region: 'north-america' },
  { id: 'haiti', name: 'Haiti', region: 'north-america' },
  { id: 'honduras', name: 'Honduras', region: 'north-america' },
  { id: 'jamaica', name: 'Jamaica', region: 'north-america' },
  { id: 'mexico', name: 'Mexico', region: 'north-america' },
  { id: 'nicaragua', name: 'Nicaragua', region: 'north-america' },
  { id: 'panama', name: 'Panama', region: 'north-america' },
  { id: 'saint-kitts-nevis', name: 'Saint Kitts and Nevis', region: 'north-america' },
  { id: 'saint-lucia', name: 'Saint Lucia', region: 'north-america' },
  { id: 'saint-vincent-grenadines', name: 'Saint Vincent and the Grenadines', region: 'north-america' },
  { id: 'trinidad-tobago', name: 'Trinidad and Tobago', region: 'north-america' },
  { id: 'united-states', name: 'United States', region: 'north-america' },

  // South America (12 countries)
  { id: 'argentina', name: 'Argentina', region: 'south-america' },
  { id: 'bolivia', name: 'Bolivia', region: 'south-america' },
  { id: 'brazil', name: 'Brazil', region: 'south-america' },
  { id: 'chile', name: 'Chile', region: 'south-america' },
  { id: 'colombia', name: 'Colombia', region: 'south-america' },
  { id: 'ecuador', name: 'Ecuador', region: 'south-america' },
  { id: 'guyana', name: 'Guyana', region: 'south-america' },
  { id: 'paraguay', name: 'Paraguay', region: 'south-america' },
  { id: 'peru', name: 'Peru', region: 'south-america' },
  { id: 'suriname', name: 'Suriname', region: 'south-america' },
  { id: 'uruguay', name: 'Uruguay', region: 'south-america' },
  { id: 'venezuela', name: 'Venezuela', region: 'south-america' },

  // Oceania (14 countries)
  { id: 'australia', name: 'Australia', region: 'oceania' },
  { id: 'fiji', name: 'Fiji', region: 'oceania' },
  { id: 'kiribati', name: 'Kiribati', region: 'oceania' },
  { id: 'marshall-islands', name: 'Marshall Islands', region: 'oceania' },
  { id: 'micronesia', name: 'Micronesia', region: 'oceania' },
  { id: 'nauru', name: 'Nauru', region: 'oceania' },
  { id: 'new-zealand', name: 'New Zealand', region: 'oceania' },
  { id: 'palau', name: 'Palau', region: 'oceania' },
  { id: 'papua-new-guinea', name: 'Papua New Guinea', region: 'oceania' },
  { id: 'samoa', name: 'Samoa', region: 'oceania' },
  { id: 'solomon-islands', name: 'Solomon Islands', region: 'oceania' },
  { id: 'tonga', name: 'Tonga', region: 'oceania' },
  { id: 'tuvalu', name: 'Tuvalu', region: 'oceania' },
  { id: 'vanuatu', name: 'Vanuatu', region: 'oceania' },
];

// Helper functions
export const getRegionById = (id: string): Region | undefined => {
  return REGIONS.find(region => region.id === id);
};

export const getCountryById = (id: string): Country | undefined => {
  return COUNTRIES.find(country => country.id === id);
};

export const getCountriesByRegion = (regionId: string): Country[] => {
  return COUNTRIES.filter(country => country.region === regionId).sort((a, b) => a.name.localeCompare(b.name));
};
